#!/bin/bash
#
# Copyright (C) 2020 Francis Deslauriers <francis.deslauriers@efficios.com>
#
# SPDX-License-Identifier: LGPL-2.1-only

CURDIR=$(dirname "$0")/
TESTDIR=$CURDIR/../../../

SH_TAP=1

# shellcheck source=../../../utils/utils.sh
source "$TESTDIR/utils/utils.sh"
# shellcheck source=./util_event_generator.sh

FULL_LTTNG_BIN="${TESTDIR}/../src/bin/lttng/${LTTNG_BIN}"

NUM_TESTS=13

plan_tests $NUM_TESTS

function test_map_ust_per_uid_create()
{
	local MAP_NAME="my_map_name"
	local MAP_NAME_2="my_map_name2"
	local MAP_NAME_3="my_map_name3"
	local SESSION_NAME="my_session_name"

	diag "Map creation"

	create_lttng_session_ok "$SESSION_NAME"

	"$FULL_LTTNG_BIN" add-map --userspace --bitness 32 --session "wrong_session_name" "$MAP_NAME" > /dev/null
	isnt $? 0 "Map creation failed on wrong session name"

	"$FULL_LTTNG_BIN" add-map --userspace --bitness 42 --session "$SESSION_NAME" "$MAP_NAME" > /dev/null
	isnt $? 0 "Map creation failed \"--bitness\" wrong value as expected"

	"$FULL_LTTNG_BIN" add-map --userspace --session "SESS_DOESNT_EXIST" "$MAP_NAME" > /dev/null
	isnt $? 0 "Failed to add map to session that doesn't exist"

	"$FULL_LTTNG_BIN" disable-map --userspace --session "$SESSION_NAME" "MAP_DOESNT_EXIST" > /dev/null
	isnt $? 0 "Failed to disable map that doesn't exist"

	"$FULL_LTTNG_BIN" add-map --userspace --bitness 64 --session "$SESSION_NAME" "$MAP_NAME" > /dev/null
	ok $? "Map with 64bit bitness created succesfully"

	"$FULL_LTTNG_BIN" disable-map --userspace "$MAP_NAME" > /dev/null
	ok $? "Map disabled succesfully"

	destroy_lttng_session_ok "$SESSION_NAME"
}

function test_map_ust_per_pid_create()
{
	local MAP_NAME="my_map_name"
	local SESSION_NAME="my_session_name"

	diag "Map per-pid creation"

	create_lttng_session_ok "$SESSION_NAME"

	lttng_add_map_ok "$MAP_NAME" "$SESSION_NAME" --userspace 64 --per-pid

	"$FULL_LTTNG_BIN" disable-map --userspace "$MAP_NAME" > /dev/null
	ok $? "Map disabled succesfully"

	"$FULL_LTTNG_BIN" enable-map --userspace "$MAP_NAME" > /dev/null
	ok $? "Map enabled succesfully"

	destroy_lttng_session_ok "$SESSION_NAME"
}

start_lttng_sessiond_notap

test_map_ust_per_uid_create
test_map_ust_per_pid_create

stop_lttng_sessiond_notap
